# .streamlit/secrets.toml

[gspread_service_account]
type = "service_account"
project_id = "talentscout-api-470412"
private_key_id = "941584a1d23c6759aee9fdc561de26501371b768"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDTTogvBucHH73u
...rest of your key...
-----END PRIVATE KEY-----"""
client_email = "streamlit-bot-service@talentscout-api-470412.iam.gserviceaccount.com"
client_id = "115798237467452696062"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-bot-service%40talentscout-api-470412.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[GROQ]
API_KEY = "YOUR_GROQ_API_KEY"

[GOOGLE_SHEET]
NAME = "Talentscout Responses"
